In [1]:
import pandas as pd
import numpy as np
url = "https://raw.githubusercontent.com/WalePhenomenon/climate_change/master/fuel_ferc1.csv"
fuel = pd.read_csv(url)
fuel.head()

record_id  ...  fuel_cost_per_mmbtu
0   f1_fuel_1994_12_1_0_7  ...                1.121
1  f1_fuel_1994_12_1_0_10  ...                1.120
2   f1_fuel_1994_12_2_0_1  ...                1.650
3   f1_fuel_1994_12_2_0_7  ...                1.970
4  f1_fuel_1994_12_2_0_10  ...                2.570

[5 rows x 11 columns]

In [2]:
print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [3]:
# Which of the following fuel type code has the lowest average fuel cost per unit burned?
average = fuel.groupby("fuel_type_code_pudl")[['fuel_cost_per_unit_burned']].mean() 
print(average.sort_values("fuel_cost_per_unit_burned")) 
# answer is gas

                     fuel_cost_per_unit_burned
fuel_type_code_pudl                           
gas                                  13.659397
other                                18.253856
waste                                19.518122
coal                                 67.421830
oil                                 168.877086
nuclear                            4955.157002


In [4]:
# What is the standard deviation and 75th percentile of the measure of energy per unit (Fuel_mmbtu_per_unit) in two decimal places?
print(fuel["fuel_mmbtu_per_unit"].describe())
# answer std=10.6 and 75 percentile is 17.006000

count    29523.000000
mean         8.492111
std         10.600220
min          0.000001
25%          1.024000
50%          5.762694
75%         17.006000
max        341.260000
Name: fuel_mmbtu_per_unit, dtype: float64


In [5]:
# What is the skewness and kurtosis for the fuel quantity burned in two decimal places?
print(fuel["fuel_qty_burned"].skew(),fuel["fuel_qty_burned"].kurt())
# answers are 15.85 and 651.37 respectively

15.851495469109503 651.3694501337732


In [6]:
# Which feature has missing values and what is the total number of missing value and percentage of the missing rows as a factor of the total number of rows in three decimal places?
print(fuel.isnull().sum())

record_id                         0
utility_id_ferc1                  0
report_year                       0
plant_name_ferc1                  0
fuel_type_code_pudl               0
fuel_unit                       180
fuel_qty_burned                   0
fuel_mmbtu_per_unit               0
fuel_cost_per_unit_burned         0
fuel_cost_per_unit_delivered      0
fuel_cost_per_mmbtu               0
dtype: int64


In [7]:
print(fuel.iloc[-1])
# index is 29522 so total is 29523

record_id                       f1_fuel_2018_12_12_1_14
utility_id_ferc1                                     12
report_year                                        2018
plant_name_ferc1                        wygen 3 bhp 52%
fuel_type_code_pudl                                 gas
fuel_unit                                           mcf
fuel_qty_burned                                   17853
fuel_mmbtu_per_unit                               1.059
fuel_cost_per_unit_burned                             0
fuel_cost_per_unit_delivered                          0
fuel_cost_per_mmbtu                               11.68
Name: 29522, dtype: object


In [8]:
print(180/29523) #0.00609694136774718
# answer is 0.006 to three decimal places

0.00609694136774718


In [9]:
#categorical == fuel unit and mode imputation would be used

In [10]:
# Which of the features has the second and third lowest correlation with the Fuel Cost Per Unit Burned?
corr = fuel.corr()
corr["fuel_cost_per_unit_burned"].sort_values()[1:3]
# answer is fuel_qty_burned and fuel_mmbtu_per_unit

fuel_qty_burned       -0.018535
fuel_mmbtu_per_unit   -0.010034
Name: fuel_cost_per_unit_burned, dtype: float64

In [11]:
#For the fuel type coal, what is the percentage change in the fuel cost per unit burned in 1998 compared to 1994?


coal = fuel.loc[fuel["fuel_type_code_pudl"] =="coal"]
years_dict={ 1994:0 , 1998:0 } # all coal burned in 1994 then 1998 

for index, row in coal.iterrows():
    if row["report_year"]in years_dict.keys():
      years_dict[row["report_year"]] += row["fuel_cost_per_unit_burned"]

difference = years_dict[1994]- years_dict[1998] 
sum = years_dict[1998]+ years_dict[1994]
percentage = (difference / sum) * 100
print(percentage)
coal
# answer is plus or minus 11.46262367748719 but I chose 18 because I couldn't fully implement the code before time was out

11.46262367748719


record_id  ...  fuel_cost_per_mmbtu
0         f1_fuel_1994_12_1_0_7  ...                1.121
1        f1_fuel_1994_12_1_0_10  ...                1.120
2         f1_fuel_1994_12_2_0_1  ...                1.650
3         f1_fuel_1994_12_2_0_7  ...                1.970
5        f1_fuel_1994_12_2_0_13  ...                1.850
...                         ...  ...                  ...
29503  f1_fuel_2018_12_191_1_14  ...                1.497
29510   f1_fuel_2018_12_403_0_2  ...                1.130
29516    f1_fuel_2018_12_12_0_8  ...                1.100
29517   f1_fuel_2018_12_12_0_10  ...                0.890
29521   f1_fuel_2018_12_12_1_13  ...                1.110

[8547 rows x 11 columns]

In [12]:
# Which year has the highest average fuel cost per unit delivered? 1997
avg_fuel_cost = fuel.groupby("report_year")[['fuel_cost_per_unit_delivered']].mean()
maximum = avg_fuel_cost['fuel_cost_per_unit_delivered'].max()
f_c_p_u_d = avg_fuel_cost['fuel_cost_per_unit_delivered']
for the_one in f_c_p_u_d.keys():
  if f_c_p_u_d[the_one] == maximum:
    print(the_one,maximum, sep="\n")
# answer is 1997

1997
11140.19723948813
